# lang_rust_skill.py
### WARNING: Currently not reviewed and adapted to git based packaging!
### Based on https://en.opensuse.org/openSUSE:Packaging_Rust_Software

SKILL_NAME = "lang_rust"

TARGET_PATTERN = r"(?i)(?:rust|cargo)"
CONTENT_PATTERN = r"(?i)(?:%\{cargo_build\}|%\{cargo_install\}|%\{cargo_test\}|cargo-packaging|vendor\.tar\.zst)"
PROMPT_PATTERN = r"(?i)(?:rust\s+(?:packag|rpm|crate)|cargo\s+(?:packag|rpm)|crate\s+rpm)"

OLLAMA_SPEC_PROMPT = """
You are an expert in Rust software RPM packaging for openSUSE. Follow the openSUSE Rust software packaging guidelines from https://en.opensuse.org/openSUSE:Packaging_Rust_Software

## BuildRequires

```
BuildRequires:  cargo
BuildRequires:  cargo-packaging
```

## ExclusiveArch

```
ExclusiveArch:  %{rust_tier1_arches}
```

## Sources

```
Source0:        %{name}-%{version}.tar.zst
Source1:        registry.tar.zst
```

Source1 is the vendored crate registry tarball generated by the `cargo_vendor` service.

## _service file

Create a `_service` file:

```
<services>
  <service name="tar_scm" mode="manual">
    <param name="url">https://github.com/user/repo.git</param>
    <param name="scm">git</param>
  </service>
  <service name="recompress" mode="manual">
    <param name="compression">zst</param>
    <param name="file">*.tar</param>
  </service>
  <service name="set_version" mode="manual"/>
  <service name="cargo_vendor" mode="manual">
    <param name="compression">zst</param>
  </service>
</services>
```

Run `osc service ra` to execute the services and generate the tarballs.

## Spec template

```
%prep
%autosetup -p1 -a1

%build
export CARGO_HOME=$PWD/.cargo
%{cargo_build}

%install
export CARGO_HOME=$PWD/.cargo
%{cargo_install}

%check
export CARGO_HOME=$PWD/.cargo
%{cargo_test}
```

## Workspace support

For workspace projects with multiple crates:

```
%build
export CARGO_HOME=$PWD/.cargo
%{cargo_build} --all

%install
export CARGO_HOME=$PWD/.cargo
%{cargo_install} -p project1
%{cargo_install} -p project2
```

## License generation

Use `cargo lock2rpmprovides` to generate license information from Cargo.lock.

## Custom Rust flags

```
%define __rustflags -C target-cpu=generic -C opt-level=3
```

## Patching vendored crates

To patch a vendored crate, add a `[patch.crates-io]` section in Cargo.toml:

```
[patch.crates-io]
foo = { path = "vendor/foo" }
```

## Key rules

- Always set `CARGO_HOME=$PWD/.cargo` before cargo commands
- Always use `%{cargo_build}`, `%{cargo_install}`, `%{cargo_test}` macros from cargo-packaging
- `ExclusiveArch: %{rust_tier1_arches}` — Rust may not build on all architectures
- Use `osc service ra` to regenerate vendor tarballs
- The build environment has NO network access — all dependencies must be vendored
"""

OLLAMA_ERROR_PROMPT = """
You are debugging a Rust RPM build failure for openSUSE.

## Common Rust build errors

### Missing cargo or cargo-packaging
```
cargo: command not found
```
→ Add `BuildRequires: cargo` and `BuildRequires: cargo-packaging`.

### Crate dependency not found
```
error[E0463]: can't find crate for `foo`
```
→ A required crate is missing from the registry tarball. Regenerate with `osc service ra`. If the crate is new, add it to the _service configuration.

### Cargo.lock issues
```
error: failed to parse lock file at: .../Cargo.lock
```
→ The Cargo.lock file is out of date or malformed. Run `cargo update` locally and regenerate the tarballs.

### Network access errors
```
error: failed to download from ...
```
→ The build environment has NO network. All dependencies must be vendored in `registry.tar.zst`. Make sure `cargo_vendor` service is in your `_service` file.

### Vendor tarball missing
```
%setup: ... registry.tar.zst: No such file or directory
```
→ Run `osc service ra` to generate the vendor tarball from the _service configuration.

### Linking with cc failed
```
= note: /usr/bin/ld: cannot find -lfoo
```
→ A native C library is missing. Add the corresponding `BuildRequires: pkgconfig(foo)` or `BuildRequires: foo-devel`.

### cargo_lock2rpmprovides not found
→ Install `cargo-packaging` or run `zypper in cargo-packaging` for the helper tools.

## Investigating interactively

If you are unsure about the root cause, include [DEEP_ANALYZE] in your response.

When inside the build environment:
- Check cargo version: `cargo --version`
- List vendored crates: `ls vendor/`
- Try building manually: `cd /home/abuild/rpmbuild/BUILD/%{name}-%{version} && CARGO_HOME=$PWD/.cargo cargo build --frozen --offline`
- Check Cargo.lock: `cat Cargo.lock | head -50`
- Check for native deps: `pkg-config --list-all | grep -i needed_lib`
"""


def fix_content(content: str) -> str:
    """Pre-build spec content fixes for common Rust packaging issues."""
    lines = content.split('\n')
    changed = False

    # 1. Add BuildRequires: cargo if %{cargo_build} is used
    has_cargo_build = any('%{cargo_build}' in l for l in lines)
    has_cargo_br = any('cargo' in l and 'BuildRequires' in l for l in lines)

    if has_cargo_build and not has_cargo_br:
        new_lines = []
        inserted = False
        for line in lines:
            new_lines.append(line)
            if not inserted and line.strip().startswith('BuildRequires'):
                new_lines.append('BuildRequires:  cargo')
                inserted = True
                changed = True
        if inserted:
            content = '\n'.join(new_lines)
            lines = content.split('\n')

    # 2. Add BuildRequires: cargo-packaging if %{cargo_build} is used
    has_cargo_pkg_br = any('cargo-packaging' in l and 'BuildRequires' in l for l in lines)
    if has_cargo_build and not has_cargo_pkg_br:
        new_lines = []
        inserted = False
        for line in lines:
            new_lines.append(line)
            if not inserted and line.strip().startswith('BuildRequires'):
                new_lines.append('BuildRequires:  cargo-packaging')
                inserted = True
                changed = True
        if inserted:
            content = '\n'.join(new_lines)

    return content
